server:
  port: 8184

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
  jpa:
    hibernate:
      ddl-auto: none
spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    platform: postgres
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:init-schema.sql,classpath:init-data.sql